import sys

lines = sys.stdin.readlines()


print(lines)

# NEED TO INSTALL C++ COMPILER
# NEED TO INSTALL C++ COMPILER
# NEED TO INSTALL C++ COMPILER
# NEED TO INSTALL C++ COMPILER
# NEED TO INSTALL C++ COMPILER